### PR TITLE
Das ist ein pull request oder so

### PR DESCRIPTION
**Pull request by rogerdarin**
Ey. Du mache akzeptier oder?

### CODE REVIEW

**Comment by dettwild** [comment]
Comment of Merging RD pull Request to my TestRepository1

**Comment by rogerdarin** [comment]
**This** is an example of _markdown_

**Comment by dettwild** [comment]
And **THIS** is an answer directly done in email ;-)
-- 
Daniel Dettwiler
Sent with Airmail

On 22 July 2015 at 17:59:25, Roger Darin (notifications@github.com) wrote:

This is an example of markdown

**Comment by rogerdarin** [comment]
This is how you do it in email

On 22 Jul 2015, at 18:10, dettwild <notifications@github.com<mailto:notifications@github.com>> wrote:

## And **THIS** is an answer directly done in email ;-)

Daniel Dettwiler
Sent with Airmail

On 22 July 2015 at 17:59:25, Roger Darin (notifications@github.commailto:notifications@github.com) wrote:

This is an example of markdown

**Pull request merged**
